name: lancet
channels:
  - conda-forge/label/dev
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - h5netcdf
  - h5py
  - joblib
  - jupyter
  - matplotlib
  - netcdf4
  - pip
  - psycopg2
  - python=3.6
  - sqlalchemy
  - dask
  - distributed
  - ipykernel
  - ipython
  - ipywidgets
  - notebook
  - numba
  - numpy
  - pandas
  - scipy
  - seaborn
  - tqdm
  - widgetsnbextension
  - xarray
  - xlrd
  - openpyxl
  - pip:
    - ecmwf-api-client

